const Team = {
  name: 'Team',
  title: 'Mannschaft',
  type: 'string',
  list: [
    {title: 'Afghanistan', value: 'AF'},
    {title: 'Ägypten', value: 'EG'},
    {title: 'Albanien', value: 'AL'},
    {title: 'Algerien', value: 'DZ'},
    {title: 'Amerikanisch-Samoa', value: 'AS'},
    {title: 'Andorra', value: 'AD'},
    {title: 'Angola', value: 'AO'},
    {title: 'Anguilla', value: 'AI'},
    {title: 'Antigua und Barbuda', value: 'AG'},
    {title: 'Äquatorialguinea', value: 'GQ'},
    {title: 'Argentinien', value: 'AR'},
    {title: 'Armenien', value: 'AM'},
    {title: 'Aruba', value: 'AW'},
    {title: 'Aserbaidschan', value: 'AZ'},
    {title: 'Äthiopien', value: 'ET'},
    {title: 'Australien', value: 'AU'},
    {title: 'Bahamas', value: 'BS'},
    {title: 'Bahrain', value: 'BH'},
    {title: 'Bangladesch', value: 'BD'},
    {title: 'Barbados', value: 'BB'},
    {title: 'Belarus', value: 'BY'},
    {title: 'Belgien', value: 'BE'},
    {title: 'Belize', value: 'BZ'},
    {title: 'Benin', value: 'BJ'},
    {title: 'Bermuda', value: 'BM'},
    {title: 'Bhutan', value: 'BT'},
    {title: 'Bolivien', value: 'BO'},
    {title: 'Bosnien und Herzegowina', value: 'BA'},
    {title: 'Botswana', value: 'BW'},
    {title: 'Brasilien', value: 'BR'},
    {title: 'Brunei', value: 'BN'},
    {title: 'Bulgarien', value: 'BG'},
    {title: 'Burkina Faso', value: 'BF'},
    {title: 'Burundi', value: 'BI'},
  ],
}

export default Team
