const Team = {
  name: 'Team',
  title: 'Mannschaft',
  type: 'string',
  options: {
    list: [
      {title: 'Afghanistan', value: 'AF'},
      {title: 'Ägypten', value: 'EG'},
      {title: 'Albanien', value: 'AL'},
      {title: 'Algerien', value: 'DZ'},
      {title: 'Amerikanisch-Samoa', value: 'AS'},
      {title: 'Andorra', value: 'AD'},
      {title: 'Angola', value: 'AO'},
      {title: 'Anguilla', value: 'AI'},
      {title: 'Antigua und Barbuda', value: 'AG'},
      {title: 'Äquatorialguinea', value: 'GQ'},
      {title: 'Argentinien', value: 'AR'},
      {title: 'Armenien', value: 'AM'},
      {title: 'Aruba', value: 'AW'},
      {title: 'Aserbaidschan', value: 'AZ'},
      {title: 'Äthiopien', value: 'ET'},
      {title: 'Australien', value: 'AU'},
      {title: 'Bahamas', value: 'BS'},
      {title: 'Bahrain', value: 'BH'},
      {title: 'Bangladesch', value: 'BD'},
      {title: 'Barbados', value: 'BB'},
      {title: 'Belarus', value: 'BY'},
      {title: 'Belgien', value: 'BE'},
      {title: 'Belize', value: 'BZ'},
      {title: 'Benin', value: 'BJ'},
      {title: 'Bermuda', value: 'BM'},
      {title: 'Bhutan', value: 'BT'},
      {title: 'Bolivien', value: 'BO'},
      {title: 'Bosnien und Herzegowina', value: 'BA'},
      {title: 'Botswana', value: 'BW'},
      {title: 'Brasilien', value: 'BR'},
      {title: 'Brunei', value: 'BN'},
      {title: 'Bulgarien', value: 'BG'},
      {title: 'Burkina Faso', value: 'BF'},
      {title: 'Burundi', value: 'BI'},
      {title: 'Cayman Islands', value: 'KY'},
      {title: 'Chile', value: 'CL'},
      {title: 'China (Volksrepublik)', value: 'CN'},
      {title: 'Chinesisch Taipeh', value: 'TW-OLY'},
      {title: 'Cook-Inseln', value: 'CK'},
      {title: 'Costa Rica', value: 'CR'},
      {title: 'Curaçao', value: 'CW'},
      {title: 'Dänemark', value: 'DK'},
      {title: 'Deutschland', value: 'DE'},
      {title: 'Dominica', value: 'DM'},
      {title: 'Dominikanische Republik', value: 'DO'},
      {title: 'Dschibuti', value: 'DJ'},
      {title: 'Ecuador', value: 'EC'},
      {title: 'Elfenbeinküste', value: 'CI'},
      {title: 'El Salvador', value: 'SV'},
      {title: 'England', value: 'GB-ENG'},
      {title: 'Eritrea', value: 'ER'},
      {title: 'Estland', value: 'EE'},
      {title: 'Eswatini', value: 'SZ'},
      {title: 'Fidschi', value: 'FJ'},
      {title: 'Finnland', value: 'FI'},
      {title: 'Frankreich', value: 'FR'},
      {title: 'Gabun', value: 'GA'},
      {title: 'Gambia', value: 'GM'},
      {title: 'Georgien', value: 'GE'},
      {title: 'Ghana', value: 'GH'},
      {title: 'Gibraltar', value: 'GI'},
      {title: 'Grenada', value: 'GD'},
      {title: 'Griechenland', value: 'GR'},
      {title: 'Guam', value: 'GU'},
      {title: 'Guatemala', value: 'GT'},
      {title: 'Guyana', value: 'GY'},
      {title: 'Guinea', value: 'GN'},
      {title: 'Guinea-Bissau', value: 'GW'},
      {title: 'Haiti', value: 'HT'},
      {title: 'Honduras', value: 'HN'},
      {title: 'Hongkong', value: 'HK'},
      {title: 'Indien', value: 'IN'},
      {title: 'Indonesien', value: 'ID'},
      {title: 'Irak', value: 'IQ'},
      {title: 'Iran', value: 'IR'},
      {title: 'Irland', value: 'IE'},
      {title: 'Island', value: 'IS'},
      {title: 'Israel', value: 'IL'},
      {title: 'Italien', value: 'IT'},
    ],
  },
}

export default Team
